### ISSUE TITLE
Support for Federation v2

### ISSUE THREAD

**Issue by YassinEldeeb** [the-guild-org/conductor#189]
```[tasklist]
### Tasks
- [x] `@inaccessible`
- [ ] `@join__type(:resolvable)`
- [ ] `@join__field(:override)`
-  [ ] `@join__type(:isInterfaceObject) `
```
