### ISSUE TITLE
smoke testing

### ISSUE THREAD

**Issue by dotansimha** [the-guild-org/conductor#245]
We should add a test that gets an `endpoint` and runs some sanity checks against it.
This way we can find critical runtime issues (wasm might fail at runtime, actix-web might throw a slient error in case of invalid `Data`, etc..). 

```[tasklist]
### Tasks
- [ ] Setup a generic test suite
- [ ] Add CI check for WASM runtime. 
- [ ] Add CI check for binary (actix) runtime 
```
