### ISSUE TITLE
`graphql` source: introspect the server (or load remote/local introspection)

### ISSUE THREAD

**Issue by dotansimha** [the-guild-org/conductor#4]
Ideally, we want a `graphql` source to be able to load introspection for the source. 

These are the options we need: 

### Load from source (default)

(default)

```
sources:
  - id: countries
    type: graphql
    config:
      endpoint: https://countries.trevorblades.com/
```

or 

```
sources:
  - id: countries
    type: graphql
    config:
      endpoint: https://countries.trevorblades.com/
      introspection:
        from: source
```

or, with custom headers:

```
sources:
  - id: countries
    type: graphql
    config:
      endpoint: https://countries.trevorblades.com/
      introspection:
        from: source
        headers:
           X-Admin-Key: 123
```

or, with polling:

```
sources:
  - id: countries
    type: graphql
    config:
      endpoint: https://countries.trevorblades.com/
      introspection:
        from: source
        polling_interval: 60
```

### Load from a remote JSON file (local or remote)

remote: 

```
sources:
  - id: countries
    type: graphql
    config:
      endpoint: https://countries.trevorblades.com/
      introspection:
        from: json
        location: https://countries.trevorblades.com/introspection.json
```

local: 

```
sources:
  - id: countries
    type: graphql
    config:
      endpoint: https://countries.trevorblades.com/
      introspection:
        from: json
        location: /file-system/introspection.json
```
```[tasklist]
### Tasks
- [ ] Load introspection from the source
- [ ] Support for custom introspection headers
- [ ] Support for polling
- [ ] Load introspection from remote JSON file
- [ ] Load introspection from local JSON file
```
