### ISSUE TITLE
Support for Supergraph (Apollo) / Fed

### ISSUE THREAD

**Issue by dotansimha** [the-guild-org/conductor#7]
The goal is to create a new `source` that allows us to load Supergraph as a source. 

This comes with a set of other requirements: 

```[tasklist]
### Tasks
- [x] Load Supergraph either from a file, env var, or remote (Apollo Studio or Hive)
- [x] Implement a Query Planner for Federation v2
- [x] Implement the plan execution
```
