### ISSUE TITLE
Persisted Operations

### ISSUE THREAD

**Issue by dotansimha** [the-guild-org/conductor#9]
requires https://github.com/the-guild-org/conductor-t2/issues/8 

The goal is to allow running persisted operations by using a hash, and then forward the original query to the upstream. 

```[tasklist]
### Tasks
- [x] Initial implementation to allow users to run persisted operations
- [x] Allow users to forbid running non-persisted operations
- [x] Store: Load from JSON (local/remote)
```
